# Generated by Django 4.2.28 on 2026-02-27 13:24

import core.utils
import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0036_alter_claim_admin_delete_claimadmin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0010_rename_servicelinkeditem_serviceitem_parent_and_more'),
        ('biometric_verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalClaimFacialAudit',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('similarity_score', models.FloatField(help_text='Similarity score between 0.0 (different) and 1.0 (identical)')),
                ('threshold_used', models.FloatField(default=0.4, help_text='Confidence threshold used for this verification')),
                ('is_verified', models.BooleanField(help_text='True if verification succeeded (similarity_score >= threshold_used)')),
                ('step_name', models.CharField(db_index=True, help_text="Name of the care journey step (e.g. 'reception', 'consultation', 'pharmacy')", max_length=100)),
                ('device_id', models.CharField(blank=True, help_text='Identifier of the device that performed the verification', max_length=255, null=True)),
                ('audit_date', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Date and time of the biometric checkpoint')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (provider, model_name, etc.)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('claim', models.ForeignKey(blank=True, db_constraint=False, help_text='The claim associated with this biometric checkpoint', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='claim.claim')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, db_constraint=False, help_text='The specific medical service related to this checkpoint', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='medical.service')),
                ('user_created', models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Claim Facial Audit',
                'verbose_name_plural': 'historical Claim Facial Audits',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ClaimFacialAudit',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('similarity_score', models.FloatField(help_text='Similarity score between 0.0 (different) and 1.0 (identical)')),
                ('threshold_used', models.FloatField(default=0.4, help_text='Confidence threshold used for this verification')),
                ('is_verified', models.BooleanField(help_text='True if verification succeeded (similarity_score >= threshold_used)')),
                ('step_name', models.CharField(db_index=True, help_text="Name of the care journey step (e.g. 'reception', 'consultation', 'pharmacy')", max_length=100)),
                ('device_id', models.CharField(blank=True, help_text='Identifier of the device that performed the verification', max_length=255, null=True)),
                ('audit_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time of the biometric checkpoint')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (provider, model_name, etc.)')),
                ('claim', models.ForeignKey(help_text='The claim associated with this biometric checkpoint', on_delete=django.db.models.deletion.CASCADE, related_name='facial_audits', to='claim.claim')),
                ('service', models.ForeignKey(blank=True, help_text='The specific medical service related to this checkpoint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facial_audits', to='medical.service')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Claim Facial Audit',
                'verbose_name_plural': 'Claim Facial Audits',
                'db_table': 'claim_facial_audit',
                'ordering': ['-audit_date'],
                'indexes': [models.Index(fields=['claim', 'audit_date'], name='claim_facia_claim_i_34a16f_idx'), models.Index(fields=['claim', 'is_verified'], name='claim_facia_claim_i_09da71_idx'), models.Index(fields=['step_name', 'audit_date'], name='claim_facia_step_na_3b6c53_idx')],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.utils.CachedModelMixin, models.Model),
        ),
    ]
