# Generated by Django 4.2.28 on 2026-03-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_verification', '0002_historicalclaimfacialaudit_claimfacialaudit'),
    ]

    operations = [
    ]
