# Generated by Django 4.2.28 on 2026-03-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_verification', '0003_add_embedding_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricembedding',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Complete configuration used to compute this embedding (detector_backend, enforce_detection, etc.).'),
        ),
    ]
